name:                haskell-elgato-streamdeck
version:             0.1.0.0
github:              "bendo/haskell-elgato-streamdeck"
license:             BSD3
author:              "Zdenko Osina"
maintainer:          "zdeno.osina@gmail.com"
copyright:           "2022 Zdenko Osina"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bendo/haskell-elgato-streamdeck#readme>

dependencies:
- base >= 4.7 && < 5
- hidapi
- bytestring

library:
  source-dirs: src

executables:
  haskell-elgato-streamdeck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-elgato-streamdeck

tests:
  haskell-elgato-streamdeck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-elgato-streamdeck
